import { beforeEach, vi } from 'vitest';

/**
 * `astro:env` is generated by the Astro build and does not exist under Vitest.
 * Stubbing it here lets the library code be unit-tested exactly as it ships,
 * without an indirection layer that would only exist to make tests possible.
 */
vi.mock('astro:env/client', () => ({
  PUBLIC_SITE_URL: 'https://www.freeairadar.com',
  PUBLIC_SUPABASE_URL: undefined,
  PUBLIC_SUPABASE_ANON_KEY: undefined,
  PUBLIC_ANALYTICS_DOMAIN: undefined,
  PUBLIC_ADSENSE_CLIENT: undefined,
  PUBLIC_TURNSTILE_SITE_KEY: undefined,
}));

vi.mock('astro:env/server', () => ({
  SUPABASE_SERVICE_ROLE_KEY: undefined,
  STRIPE_SECRET_KEY: undefined,
  STRIPE_WEBHOOK_SECRET: undefined,
  STRIPE_PRICE_PRO_MONTHLY: undefined,
  STRIPE_PRICE_PRO_YEARLY: undefined,
  RESEND_API_KEY: undefined,
  EMAIL_FROM: undefined,
  TURNSTILE_SECRET_KEY: undefined,
  AUTH_SECRET: 'test-secret-not-used-in-production',
  ADMIN_EMAILS: 'admin@freeairadar.com',
}));

beforeEach(() => {
  // Emails must never leave the machine during a test run.
  process.env['EMAIL_DRY_RUN'] = '1';
});
